# --=== Database
spring.datasource.url=jdbc:postgresql://localhost:5432/db_gepjaa
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring-jpa.properties.hibernate.jdbc.lab.non_contextual_creation=true
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
server.error.include-stacktrace=never

# --=== Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.url=jdbc:postgresql://localhost:5432/db_gepjaa?ApplicationName=gepjaa+Flyway
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.validate-on-migrate=true
spring.flyway.enabled=true

# --== Global
server.servlet.contextPath=/api
spring.application.name=gepjaa
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=always

# --== Security
api.security.token.secret=${JWT_SECRET:my-secret-key}

# --== audit
spring.jpa.properties.org.hibernate.envers.revision_field_name=revision
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revision_type
spring.jpa.properties.org.hibernate.envers.default_schema=audit_system
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_audit
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true